# Generated by Django 6.0.4 on 2026-05-01 13:53

import coringa.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Razão social do provedor"
                    ),
                ),
                (
                    "data_expiracao",
                    models.DateTimeField(verbose_name="Data e hora da expiração"),
                ),
                (
                    "secret",
                    models.CharField(
                        default=coringa.models.gerar_secret,
                        editable=False,
                        max_length=16,
                        unique=True,
                        verbose_name="Secret",
                    ),
                ),
                ("observacao", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de cadastro"
                    ),
                ),
                (
                    "data_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data atualização"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("expirado", "Expirado"),
                            ("desativado", "Desativado"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                (
                    "responsavel_cadastro",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provedor de internet",
                "verbose_name_plural": "Provedores de internet",
            },
        ),
        migrations.CreateModel(
            name="ClienteIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endereco_ip",
                    models.CharField(
                        help_text="Exemplo: 192.168.122.2",
                        max_length=18,
                        validators=[coringa.models.validar_ip],
                        verbose_name="Endereço IP/Rede",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Lista_ips",
                        to="coringa.cliente",
                        verbose_name="Provedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP do cliente",
                "verbose_name_plural": "IPs dos clientes",
            },
        ),
    ]
