# Generated by Django 6.0.4 on 2026-05-31 15:48

import os
from django.conf import settings
from django.db import migrations

def create_radius_tables_if_needed(connection):
    schema_path = os.path.join(settings.BASE_DIR, 'freeradius', 'schema.sql')
    if os.path.exists(schema_path):
        with open(schema_path, 'r') as f:
            sql_content = f.read()
        
        statements = []
        current_statement = []
        for line in sql_content.split('\n'):
            cleaned_line = line.strip()
            if not cleaned_line or cleaned_line.startswith('#') or cleaned_line.startswith('--'):
                continue
            current_statement.append(line)
            if cleaned_line.endswith(';'):
                statements.append('\n'.join(current_statement))
                current_statement = []
                
        with connection.cursor() as cursor:
            for statement in statements:
                if statement.strip():
                    cursor.execute(statement)

def sync_radius_tables(apps, schema_editor):
    from django.db import connection
    from django.utils import timezone
    
    # Ensure tables exist (crucial for test databases)
    create_radius_tables_if_needed(connection)
    
    Cliente = apps.get_model('coringa', 'Cliente')
    ClienteIP = apps.get_model('coringa', 'ClienteIP')
    
    active_ips = ClienteIP.objects.filter(cliente__status='ativo')
    
    with connection.cursor() as cursor:
        for ip in active_ips:
            # Check if exists in nas
            cursor.execute("SELECT id FROM nas WHERE nasname = %s", [ip.endereco_ip])
            row = cursor.fetchone()
            if row:
                cursor.execute(
                    "UPDATE nas SET shortname = %s, secret = %s, description = %s WHERE nasname = %s",
                    [ip.cliente.nome[:32], ip.cliente.secret, f"Cliente: {ip.cliente.nome}"[:200], ip.endereco_ip]
                )
            else:
                cursor.execute(
                    "INSERT INTO nas (nasname, shortname, secret, description) VALUES (%s, %s, %s, %s)",
                    [ip.endereco_ip, ip.cliente.nome[:32], ip.cliente.secret, f"Cliente: {ip.cliente.nome}"[:200]]
                )
            
            # Update/Insert reload time
            clean_ip = ip.endereco_ip.split('/')[0][:15]
            cursor.execute("SELECT nasipaddress FROM nasreload WHERE nasipaddress = %s", [clean_ip])
            if cursor.fetchone():
                cursor.execute(
                    "UPDATE nasreload SET reloadtime = %s WHERE nasipaddress = %s",
                    [timezone.now(), clean_ip]
                )
            else:
                cursor.execute(
                    "INSERT INTO nasreload (nasipaddress, reloadtime) VALUES (%s, %s)",
                    [clean_ip, timezone.now()]
                )
        
        # Populate wildcard default in radcheck if it doesn't exist
        cursor.execute("SELECT id FROM radcheck WHERE username = 'DEFAULT'")
        if not cursor.fetchone():
            cursor.execute(
                "INSERT INTO radcheck (username, attribute, op, value) VALUES (%s, %s, %s, %s)",
                ['DEFAULT', 'Auth-Type', ':=', 'Accept']
            )

def reverse_sync(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM radcheck WHERE username = 'DEFAULT'")

class Migration(migrations.Migration):

    dependencies = [
        ("coringa", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(sync_radius_tables, reverse_code=reverse_sync),
    ]

