# Generated by Django 6.0.4 on 2026-05-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coringa", "0002_auto_20260531_1248"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nasname", models.CharField(max_length=128)),
                ("shortname", models.CharField(blank=True, max_length=32, null=True)),
                ("type", models.CharField(default="other", max_length=30)),
                ("ports", models.IntegerField(blank=True, null=True)),
                ("secret", models.CharField(default="secret", max_length=60)),
                ("server", models.CharField(blank=True, max_length=64, null=True)),
                ("community", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(default="RADIUS Client", max_length=200),
                ),
            ],
            options={
                "db_table": "nas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Nasreload",
            fields=[
                (
                    "nasipaddress",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("reloadtime", models.DateTimeField()),
            ],
            options={
                "db_table": "nasreload",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Radcheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=64)),
                ("attribute", models.CharField(default="", max_length=64)),
                ("op", models.CharField(default="==", max_length=2)),
                ("value", models.CharField(default="", max_length=253)),
            ],
            options={
                "db_table": "radcheck",
                "managed": False,
            },
        ),
    ]
