# Generated by Django 6.0.4 on 2026-06-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coringa", "0003_nas_nasreload_radcheck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("expirado", "Expirado"),
                    ("desativado", "Desativado"),
                    ("inativo", "Inativo"),
                ],
                default="ativo",
                max_length=10,
            ),
        ),
    ]
