# Generated by Django 6.0.4 on 2026-06-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coringa", "0004_alter_cliente_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radpostauth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("pass_field", models.CharField(db_column="pass", max_length=64)),
                ("reply", models.CharField(max_length=32)),
                (
                    "nas_ip_address",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("authdate", models.DateTimeField()),
                (
                    "class_field",
                    models.CharField(
                        blank=True, db_column="class", max_length=64, null=True
                    ),
                ),
            ],
            options={
                "db_table": "radpostauth",
                "managed": False,
            },
        ),
    ]
