# Generated by Django 6.0.4 on 2026-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coringa", "0005_radpostauth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radacct",
            fields=[
                ("radacctid", models.BigAutoField(primary_key=True, serialize=False)),
                ("acctsessionid", models.CharField(default="", max_length=64)),
                (
                    "acctuniqueid",
                    models.CharField(default="", max_length=32, unique=True),
                ),
                ("username", models.CharField(default="", max_length=64)),
                (
                    "realm",
                    models.CharField(blank=True, default="", max_length=64, null=True),
                ),
                ("nasipaddress", models.CharField(default="", max_length=15)),
                ("nasportid", models.CharField(blank=True, max_length=32, null=True)),
                ("nasporttype", models.CharField(blank=True, max_length=32, null=True)),
                ("acctstarttime", models.DateTimeField(blank=True, null=True)),
                ("acctupdatetime", models.DateTimeField(blank=True, null=True)),
                ("acctstoptime", models.DateTimeField(blank=True, null=True)),
                ("acctinterval", models.IntegerField(blank=True, null=True)),
                ("acctsessiontime", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "acctauthentic",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "connectinfo_start",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "connectinfo_stop",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("acctinputoctets", models.BigIntegerField(blank=True, null=True)),
                ("acctoutputoctets", models.BigIntegerField(blank=True, null=True)),
                ("calledstationid", models.CharField(default="", max_length=50)),
                ("callingstationid", models.CharField(default="", max_length=50)),
                ("acctterminatecause", models.CharField(default="", max_length=32)),
                ("servicetype", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "framedprotocol",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("framedipaddress", models.CharField(default="", max_length=15)),
                ("framedipv6address", models.CharField(default="", max_length=45)),
                ("framedipv6prefix", models.CharField(default="", max_length=45)),
                ("framedinterfaceid", models.CharField(default="", max_length=44)),
                ("delegatedipv6prefix", models.CharField(default="", max_length=45)),
                (
                    "class_field",
                    models.CharField(
                        blank=True, db_column="class", max_length=64, null=True
                    ),
                ),
            ],
            options={
                "db_table": "radacct",
                "managed": False,
            },
        ),
    ]
