# Generated by Django 6.0.4 on 2026-06-20 17:40

import coringa.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coringa", "0006_radacct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radippool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_name", models.CharField(max_length=30)),
                ("framedipaddress", models.CharField(max_length=15)),
                ("nasipaddress", models.CharField(default="", max_length=15)),
                ("calledstationid", models.CharField(default="", max_length=30)),
                ("callingstationid", models.CharField(default="", max_length=30)),
                ("expiry_time", models.DateTimeField(blank=True, null=True)),
                ("username", models.CharField(default="", max_length=64)),
                ("pool_key", models.CharField(default="", max_length=30)),
            ],
            options={
                "verbose_name": "IP da Pool",
                "verbose_name_plural": "IPs da Pool",
                "db_table": "radippool",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="habilitar_pool",
            field=models.BooleanField(
                default=False, verbose_name="Habilitar entrega de IP por Pool"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pool_block",
            field=models.CharField(
                blank=True,
                help_text="Exemplo: 192.168.100.0/24",
                max_length=18,
                null=True,
                validators=[coringa.models.validar_ip],
                verbose_name="Bloco de IP da Pool",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="pool_name_input",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nome da Pool"
            ),
        ),
    ]
