# Generated by Django 6.0.4 on 2026-06-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "coringa",
            "0007_radippool_cliente_habilitar_pool_cliente_pool_block_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="radippool",
            options={
                "managed": False,
                "verbose_name": "IP da Pool",
                "verbose_name_plural": "IPs da Pool",
            },
        ),
    ]
